### ISSUE TITLE
Unexpected "=" in settings.ini

### ISSUE THREAD

**Issue by ChildishAlbino** [mescon/Muximux#162]
Just installed Muximux and having an issue whenever I save the settings, receiving this error when I try to load the ui.

`Warning: syntax error, unexpected '=' in settings.ini.php on line 100 in C:\nginx\html\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php on line 134

Fatal error: Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: settings.ini.php in C:\nginx\html\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php:136 Stack trace: #0 C:\nginx\html\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php(894): Config_Lite->read('settings.ini.ph...', 0) #1 C:\nginx\html\index.php(10): Config_Lite->__construct('settings.ini.ph...') #2 {main} thrown in C:\nginx\html\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php on line 136`

When I go to the settings file I find this below my servers.
`[secret]
 = "muximux-59a19d82c051d7.33294141"

[function]
 = "write_ini"
`

If I delete these lines everything runs perfectly, but as soon as I change a setting and save it these lines are added again and run the same error.

**Comment by stevens-r** [comment]
i just started having this problem after i updated yesterday  /var/log/apache2/error.log
`[Sun Aug 27 12:28:17.357968 2017] [:error] [pid 24943] [client 209.126.136.4:48798] PHP Warning:  syntax error, unexpected '=' in settings.ini.php on line 3\n in /var/www/Muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 134`

`[Sun Aug 27 12:28:17.358044 2017] [:error] [pid 24943] [client 209.126.136.4:48798] PHP Fatal error:  Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: settings.ini.php in /var/www/Muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php:136\nStack trace:\n#0 /var/www/Muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php(894): Config_Lite->read('settings.ini.ph...', 0)\n#1 /var/www/Muximux/index.php(10): Config_Lite->__construct('settings.ini.ph...')\n#2 {main}\n  thrown in /var/www/Muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 136`


line 133-139
`{`
` $this->sections = parse_ini_file($filename, $this->processSections, $mode);`
        `if (false === $this->sections) {`
            `throw new Config_Lite_Exception_Runtime(`
`'failure, can not parse the file: ' . $filename`
           ` );`
`}`

**Comment by mescon** [comment]
Muximux v2 (PHP) is no longer maintained. Muximux v3 is a complete rewrite — a standalone Go binary with a modern UI, built-in reverse proxy, themes, and 1,600+ icons. Please check the [main branch](https://github.com/mescon/Muximux) for the new version.
