### ISSUE TITLE
PHP Warning:  syntax error, unexpected $end, expecting '}' in settings.ini.php on line 2

### ISSUE THREAD

**Issue by brando56894** [mescon/Muximux#179]
I have Muximux running under a LEMP7 stack and I get the below error when trying to access the site.

`2018/02/19 18:41:36 [error] 29342#29342: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  syntax error, unexpected $end, expecting '}' in settings.ini.php on line 2
 in /usr/share/webapps/muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 134
PHP message: PHP Fatal error:  Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: settings.ini.php in /usr/share/webapps/muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php:136
Stack trace:
#0 /usr/share/webapps/muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php(894): Config_Lite->read('settings.ini.ph...', 0)
#1 /usr/share/webapps/muximux/index.php(10): Config_Lite->__construct('settings.ini.ph...')
#2 {main}
  thrown in /usr/share/webapps/muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 136" while reading response header from upstream, client: 192.168.1.42,`

**Comment by mescon** [comment]
Muximux v2 (PHP) is no longer maintained. Muximux v3 is a complete rewrite — a standalone Go binary with a modern UI, built-in reverse proxy, themes, and 1,600+ icons. Please check the [main branch](https://github.com/mescon/Muximux) for the new version.
