### ISSUE TITLE
Reinstall every 2ish weeks

### ISSUE THREAD

**Issue by stevens-r** [mescon/Muximux#185]
anyone know why muximux just stops working every 2 or so weeks 

error message i get 
www.domain.ca is currently unable to handle this request.
HTTP ERROR 500

anyone else experiencing this?

**Comment by mescon** [comment]
You'd have to check your webserver logs and see what's happening.
Have you checked settings.ini.php for any faults in there?

**Comment by wikkixwikki** [comment]
I am getting the http error 500 on my stuff now, journalctl -xe isn't showing anything helpful, all of my other docker containers work just fine with the nginx redirect. It is strictly only muximux that is having this issue.
I do have this showing in the docker logs specifically for muximux
`Stack trace:
#0 /config/www/muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php(894): Config_Lite->read('settings.ini.ph...', 0)
#1 /config/www/muximux/index.php(10): Config_Lite->__construct('settings.ini.ph...')
#2 {main}
  thrown in /config/www/muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 136" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET / HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "admin.efcinema.com"
2018/04/16 11:29:39 [error] 281#281: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  syntax error, unexpected '=' in settings.ini.php on line 3
 in /config/www/muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 134
PHP message: PHP Fatal error:  Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: settings.ini.php in /config/www/muximux/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php:136
`

The thing is that i never once had any issues until I set up a domain site and a redirect for muximux on my server. Then I added SSL. So not 100% sure why this is happening, but seems like I am not the only one.  I have not made any changes and it has also been working great the past few weeks I have set it up, then today, tried to access it and now cannot get it to go through as it gets the error.

One thing I did see in researching is this 
https://www.reddit.com/r/usenet/comments/4yyizt/muximux_dashboard_http_error_500/

One comment states 

> lol so I am working on a docker image of that exact web app right now. The php denied us coming from the authors code. copy(settings.ini.php): failed to open stream: Permission denied in /var/www/html/muximux/muximux.php on line 45 The actual line is 73 $cache_new = "; <?php die(\"Access denied\"); ?>"; // Adds this to the top of the config so that PHP kills the execution if someone tries to request the config-file I believe the author did that for security. I am not sure what exactly is going on but you can open up a bug on the github page.

**Comment by Badbabyboyo** [comment]
I'm a little late to the party but I've been experiencing this too. It seems like every couple weeks or so the settings.ini.php file has the last line plus a quotation mark from the line above removed somehow. My solution right now is to just keep a setting.ini.php.bak file in the same folder and just use the backup whenever this happens. I might do a pull request and try to figure out the bug causing this but I'm by no means a web developer so it might take me a while.

**Comment by mescon** [comment]
@Badbabyboyo if you work it out, please submit a pull request and I'd be happy to merge it!

**Comment by mescon** [comment]
Muximux v2 (PHP) is no longer maintained. Muximux v3 is a complete rewrite — a standalone Go binary with a modern UI, built-in reverse proxy, themes, and 1,600+ icons. Please check the [main branch](https://github.com/mescon/Muximux) for the new version.
